app:
  name: zenthara
  environment: development
  port: 8081
  gin_mode: debug

auth:
  api_key: API_KEY

http:
  timeout: 90s
  max_retries: 3
  retry_wait_time: 1s
  max_retry_wait_time: 5s

gpt:
  base_url: "https://api.openai.com/v1"
  api_key: OPENAI_API_KEY
  model: gpt-4
  temperature: 0.7
  top_p: 0.9
  max_tokens: 1024
  timeout: 90s

logger:
  level: debug
  format: console
